apiVersion: v1
kind: Pod
metadata:
  name: h2o-3-small
spec:
  securityContext:
    runAsUser: 2117
    fsGroup: 2117
  containers:
  - args:
    - cat
    command:
    - /bin/sh
    - -c
    image: !IMAGE_SUBST!
    imagePullPolicy: Always
    name: h2o-3-container
    resources:
      limits:
        cpu: "9.5"
        memory: 60Gi
      requests:
        cpu: "9.5"
        memory: 60Gi
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /home/0xdiag
      name: datasets
  imagePullSecrets:
  - name: regcred
  volumes:
  - hostPath:
      path: /home/0xdiag
      type: ""
    name: datasets
